# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.provider.oauth:
        class: Application\Sonata\UserBundle\Security\Core\User\OAuthUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebookID, google: googleID}]
